caterer/caterer/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'caterer.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^caterer/',include('cmanagement.urls',namespace="cmanagement")),
    url(r'^admin/', include(admin.site.urls)),
)

caterer/cmanagement/urls.py
from django.conf.urls import patterns,url

from cmanagement import views

urlpatterns = patterns('',
	url(r'^$',views.index,name='index'),
	url(r'^(?P<c_id>\d+)/$',views.details,name='details'),
	url(r'^insert/$',views.insert,name='insert'),
	url(r'^sortcost/$',views.sortcost,name='sortcost'),
	url(r'^(?P<c_id>\d+)/updates/$',views.updates,name='updates'),
	) 

caterer/cmanagement/models.py
from django.db import models
from django.forms import ModelForm
# Create your models here.

class cmanagement(models.Model):
	name = models.CharField(max_length=100)
	details = models.TextField()
	address = models.TextField()
	phone = models.CharField(max_length=20)
	cost = models.IntegerField()

class cmanagementForm(ModelForm):
	class Meta:
		model = cmanagement
		fields = ['name','details','address','phone','cost']	
			
	

caterer/cmanagement/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponseRedirect
# Create your views here.
from cmanagement.models import cmanagement,cmanagementForm

def index(request):
	if request.method== 'POST':
		c_obj = get_object_or_404(cmanagement,pk=request.POST.get('delete'))
		c_obj.delete()
		return render(request,'cmanagement/index.html',{'cmanagement':cmanagement.objects.all()})	
	else:
		latest_list = cmanagement.objects.all()
		return render(request,'cmanagement/index.html',{'cmanagement':latest_list})

def sortcost(request):
	latest_list = cmanagement.objects.order_by('cost')
	return render(request,'cmanagement/index.html',{'cmanagement':latest_list})	

def details(request,c_id):
	c_detail = get_object_or_404(cmanagement,pk=c_id)
	return render(request,'cmanagement/details.html',{'c_detail':c_detail})

def insert(request):
	if request.method == 'POST':
		form = 	cmanagementForm(request.POST)
		if form.is_valid():
			name = form.cleaned_data['name']
			phone = form.cleaned_data['phone']
			address  = form.cleaned_data['address']	
			details = form.cleaned_data['details']
			cost = form.cleaned_data['cost']
			f = cmanagement.objects.create(name=name,phone=phone,details=details,address=address,cost=int(cost))
			return render(request,'cmanagement/insert.html',{'error_msg':'Success'})
		else:
			return render(request,'cmanagement/insert.html',{'error_msg':form})	
	else:
		return render(request,'cmanagement/insert.html')		

def updates(request,c_id):
	if request.method == 'POST':
		form = 	cmanagementForm(request.POST)
		if form.is_valid():
			c_obj = get_object_or_404(cmanagement,pk=c_id)
			c_obj.name = form.cleaned_data['name']
			c_obj.phone = form.cleaned_data['phone']
			c_obj.address  = form.cleaned_data['address']	
			c_obj.details = form.cleaned_data['details']
			c_obj.cost = form.cleaned_data['cost']
			c_obj.save()
			return render(request,'cmanagement/update.html',{'succ':'Success'})
	else:
		c = get_object_or_404(cmanagement, pk=c_id)
		return render(request,'cmanagement/update.html',{'cmanagement':c })

caterer/cmanagement/templates/cmanagement/details.html
{{ c_detail.details }}

caterer/cmanagement/templates/cmanagement/index.html
{% if cmanagement %}
	<ul>
	{% for c in cmanagement %}
		<li> Name: {{ c.name }}</li>
		<li> Address: {{ c.address }}</li>
		<li> Phone: {{ c.phone }}</li>
		<li> Cost: {{ c.cost }}</li>
		<li> <a href="{% url 'cmanagement:updates' c.id %}"> Update </a> </li>
		<li> <a href="{% url 'cmanagement:details' c.id %}"> Details </a></li>

		<br />
	{% endfor %}	
	</ul>
	<form action="{% url 'cmanagement:index' %}" method="post">
	{% csrf_token %}
	<select name="delete">
	{% for c in cmanagement %}
		<option value="{{c.id}}">{{c.name}}</option>
	{% endfor %}
	</select>
	<input type="Submit" value="Delete" />
	</form>
{% else %}
	<p> No caterer </p>
{% endif %}
<br />
<p><a href="{% url 'cmanagement:insert' %}">Insert </a> </p>
<p><a href="{% url 'cmanagement:sortcost' %}">Sort Cost </a></p>	

caterer/cmanagement/templates/cmanagement/insert.html
<h2>Insert caterer's details</h2>

{% if error_msg %} <strong>{{ error_msg }} </strong> {% endif %}
<form action="{% url 'cmanagement:insert' %}" method="post">
{% csrf_token %}

	<label for="phone">Phone </label>
	<input type="text" name="phone" id="phone">
	<br />
	<label for="address">Address </label>
	<textarea name="address" id="address">Address here</textarea>
	<br />
	<label for="details">Details </label>
	<textarea name="details" id="details">Details here </textarea>
	<br />
	<label for="name">Name </label>
	<input type="text" name="name" id="name">
	<br />
	<label for="cost">Cost </label>
	<input type="text" name="cost" id="cost">
	<br />
	<input type="submit" value="Insert" />
</form>

caterer/cmanagement/templates/cmanagement/update.html
<h2>Insert caterer's details</h2>

{% if succ %} <strong>{{ succ }} </strong> {% endif %}
{% if cmanagement %}
<form action="{% url 'cmanagement:updates' cmanagement.id %}" method="post">
{% csrf_token %}

	<label for="phone">Phone </label>
	<input type="text" name="phone" id="phone" value="{{cmanagement.phone}}">
	<br />
	<label for="address">Address </label>
	<textarea name="address" id="address">{{ cmanagement.address }}</textarea>
	<br />
	<label for="details">Details </label>
	<textarea name="details" id="details">{{ cmanagement.address }}</textarea>
	<br />
	<label for="name">Name </label>
	<input type="text" name="name" id="name" value="{{cmanagement.name}}">
	<br />
	<label for="cost">Cost </label>
	<input type="text" name="cost" id="cost" value="{{cmanagement.cost}}">
	<br />
	<input type="submit" value="Update" />
</form>
{% endif %}